services:
  bp_sync:
    build:
      context: ./bp_sync
      dockerfile: Dockerfile
      target: development
    depends_on:
      seq:
        condition: service_healthy

  seq:
    image: datalust/seq:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s   # Проверять каждые 5 секунд
      timeout: 2s    # Таймаут проверки
      retries: 5     # Количество неудачных попыток перед пометкой как unhealthy
    restart: unless-stopped
