"""Initial

Revision ID: 68fd1eae6a1c
Revises:
Create Date: 2026-05-12 00:31:55.634556

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "68fd1eae6a1c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "communication_channel_types",
        sa.Column(
            "type_id",
            sa.String(length=20),
            nullable=False,
            comment="Тип коммуникации (PHONE, EMAIL, WEB, IM, LINK)",
        ),
        sa.Column(
            "value_type",
            sa.String(length=50),
            nullable=False,
            comment=(
                "Уточнение типа коммуникации по каналу "
                "(WORK, HOME, MAIN, MOBILE и т.д.)"
            ),
        ),
        sa.Column(
            "description",
            sa.String(length=255),
            nullable=True,
            comment="Описание типа канала",
        ),
        sa.Column(
            "internal_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Флаг удаления",
        ),
        sa.PrimaryKeyConstraint("internal_id"),
        sa.UniqueConstraint(
            "type_id", "value_type", name="uq_channel_type_value_type"
        ),
    )
    op.create_table(
        "departments",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False, comment="Название"),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "internal_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Флаг удаления",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["departments.external_id"],
        ),
        sa.PrimaryKeyConstraint("internal_id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "communication_channels",
        sa.Column(
            "entity_type",
            sa.String(length=20),
            nullable=False,
            comment="Тип сущности (lead, contact, company)",
        ),
        sa.Column(
            "entity_id",
            sa.Integer(),
            nullable=False,
            comment="Внешний ID соответствующей сущности",
        ),
        sa.Column(
            "channel_type_id",
            sa.UUID(),
            nullable=False,
            comment="Ссылка на тип канала",
        ),
        sa.Column(
            "value",
            sa.String(length=255),
            nullable=False,
            comment="Значение коннекта (номер телефона, email, URL и т.д.)",
        ),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "internal_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Флаг удаления",
        ),
        sa.ForeignKeyConstraint(
            ["channel_type_id"],
            ["communication_channel_types.internal_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("internal_id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_index(
        op.f("ix_communication_channels_entity_type"),
        "communication_channels",
        ["entity_type"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column(
            "xml_id", sa.String(), nullable=True, comment="Внешний код"
        ),
        sa.Column("name", sa.String(), nullable=True, comment="Имя"),
        sa.Column(
            "second_name", sa.String(), nullable=True, comment="Отчество"
        ),
        sa.Column("last_name", sa.String(), nullable=True, comment="Фамилия"),
        sa.Column(
            "personal_gender", sa.String(), nullable=True, comment="Пол"
        ),
        sa.Column(
            "work_position", sa.String(), nullable=True, comment="Должность"
        ),
        sa.Column(
            "user_type",
            sa.String(),
            nullable=True,
            comment="Тип пользователя",
        ),
        sa.Column(
            "active", sa.Boolean(), nullable=False, comment="Активность"
        ),
        sa.Column(
            "is_online", sa.Boolean(), nullable=False, comment="Онлайн"
        ),
        sa.Column(
            "last_login",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Последняя авторизация",
        ),
        sa.Column(
            "date_register",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата регистрации",
        ),
        sa.Column(
            "personal_birthday",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата рождения",
        ),
        sa.Column(
            "employment_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата принятия на работу",
        ),
        sa.Column(
            "date_new",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Новая дата",
        ),
        sa.Column(
            "time_zone", sa.String(), nullable=True, comment="Часовой пояс"
        ),
        sa.Column(
            "personal_city",
            sa.String(),
            nullable=True,
            comment="Город проживания",
        ),
        sa.Column("email", sa.String(), nullable=True, comment="E-Mail"),
        sa.Column(
            "personal_mobile",
            sa.String(),
            nullable=True,
            comment="Личный мобильный",
        ),
        sa.Column(
            "work_phone",
            sa.String(),
            nullable=True,
            comment="Телефон компании",
        ),
        sa.Column(
            "personal_www",
            sa.String(),
            nullable=True,
            comment="Домашняя страничка",
        ),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column(
            "external_id",
            sa.Integer(),
            nullable=False,
            comment="ID во внешней системе",
        ),
        sa.Column(
            "internal_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Флаг удаления",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.external_id"],
        ),
        sa.PrimaryKeyConstraint("internal_id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "managers",
        sa.Column(
            "user_id", sa.Integer(), nullable=False, comment="ИД сотрудника"
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Менеджер активный",
        ),
        sa.Column("disk_id", sa.Integer(), nullable=True, comment="ИД диска"),
        sa.Column(
            "chat_id",
            sa.Integer(),
            nullable=True,
            comment="ИД служебного чата",
        ),
        sa.Column(
            "internal_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Флаг удаления",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.external_id"],
        ),
        sa.PrimaryKeyConstraint("internal_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_auths",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="ID пользователя (UUID)",
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
            comment="Хеш пароля (bcrypt/argon2)",
        ),
        sa.Column(
            "role",
            sa.String(length=10),
            nullable=False,
            comment="Роль: admin, manager, user, guest",
        ),
        sa.Column(
            "is_verified",
            sa.Boolean(),
            nullable=False,
            comment="Email подтверждён",
        ),
        sa.Column(
            "last_login_attempt",
            sa.TIMESTAMP(timezone=True),
            nullable=True,
            comment="Время последней неудачной попытки входа",
        ),
        sa.Column(
            "internal_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="Уникальный идентификатор",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата и время последнего обновления",
        ),
        sa.Column(
            "is_deleted",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Флаг удаления",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.internal_id"],
        ),
        sa.PrimaryKeyConstraint("internal_id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_auths")
    op.drop_table("managers")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_communication_channels_entity_type"),
        table_name="communication_channels",
    )
    op.drop_table("communication_channels")
    op.drop_table("departments")
    op.drop_table("communication_channel_types")
    # ### end Alembic commands ###
